name: goals-app-services
services:
  backend:
    build: backend/
    ports:
      - '3333:3333'
    environment:
      - ENVIROMENT=DEV
    volumes: 
      - ./backend:/app
      # - nodemodules:/app/node_modules
    restart: on-failure
    depends_on: 
      - database
    links: 
      - database
  
  database:
    image: bitnami/postgresql:13.16.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=goalsapp

volumes:
  nodemodules: {}